version: "3.8"

services:
    app:
        build: .
        container_name: wh_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: laravel

            XDEBUG_MODE: debug
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes
            PHP_IDE_CONFIG: serverName=laravel-docker

        ports:
            - "8000:8000"
            - "9003:9003"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: wh_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
