version: '3.8'

services:
    app:
        image: php:8.4-fpm
        container_name: wh_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
            - XDEBUG_MODE=debug
            - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 start_with_request=yes
            - PHP_IDE_CONFIG=serverName=laravel-docker
        ports:
            - "8000:8000"
            - "9003:9003"
        command: >
            bash -c "apt-get update && apt-get install -y zip unzip git &&
            pecl install xdebug &&
            docker-php-ext-enable xdebug &&
            docker-php-ext-install pdo pdo_mysql &&
            if [ ! -f .env ]; then cp .env.example .env; fi &&
            php artisan key:generate &&
            php artisan serve --host=0.0.0.0 --port=8000"

    mysql:
        image: mysql:8.0
        container_name: wh_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
